version: "3"
services:
  jupyter:
    image: jupyter/datascience-notebook
    ports:
      - "8888:8888"
    command:
      - "start.sh"
      - "jupyter"
      - "lab"
    volumes:
      - ".:/home/jovyan/work"
